---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Utilisateur.
--- DateTime: 28/11/2025 17:24
---

--- # R* Enum
EULER_XYZ = 0
EULER_XZY = 1
EULER_YXZ = 2
EULER_YZX = 3
EULER_ZXY = 4
EULER_ZYX = 5
EULER_MAX = 6

RegisterNUICallback('getPlayerStats', function(data, cb)
    local iPlayerPed = PlayerPedId()
    local vPosition = GetEntityCoords(iPlayerPed)
    local vRotation = GetEntityRotation(iPlayerPed, EULER_YXZ)
    local iHealth = (GetEntityHealth(iPlayerPed) - 100)
    local iMaxHealth = (GetEntityMaxHealth(iPlayerPed) - 100)
    if iHealth < 0 then
        iHealth = 0
    end
    local healthPercent = math.floor((iHealth / iMaxHealth) * 100)
    local responseData = {
        health = healthPercent,
        armor = GetPedArmour(iPlayerPed),
        position = {
            x = vPosition.x,
            y = vPosition.y,
            z = vPosition.z
        },
        rotation = {
            x = vRotation.x,
            y = vRotation.y,
            z = vRotation.z
        }
    }
    cb(responseData)
end)

RegisterNUICallback('closeInterface', function(data, cb)
    SendNUIMessage({
        action = 'setVisible',
        data = false
    })
    SetNuiFocus(false, false)
    cb(true)
end)

RegisterCommand("show-interface", function()
    SendNUIMessage({
        action = 'setVisible',
        data = true
    })
    SetNuiFocus(true, true)
end)